# Generated by Django 2.0.3 on 2018-09-03 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(verbose_name='Date/time checked in')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('badge_number', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Guest'),
        ),
    ]
