# Generated by Django 2.0.3 on 2018-09-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='badge_number',
            field=models.IntegerField(max_length=5),
        ),
    ]
