# Generated by Django 2.0.3 on 2018-09-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20180903_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='id',
        ),
        migrations.AlterField(
            model_name='guest',
            name='badge_number',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
