# Generated by Django 2.0.3 on 2018-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_remove_guest_is_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
